### ISSUE TITLE
Milestone 3 (Developer ergonomics) - Proposal

### ISSUE THREAD

**Issue by wertikalk** [filecoin-project/filecoin-solidity#31]
### Description

This milestone is supposed to last 3 weeks and its purpose is to improve the UX of the developers who use this library.

Link to the original RFP: https://github.com/filecoin-project/devgrants/issues/1569

### Proposed changes

- Clear documentation
    - Currently, there’s a lot of missing useful information about the `filecoin-solidity`’s lib methods/members/types and their correct use
    - Also, the current NatSpec is not consistent (for example, missing fields about return values)

- High number of custom nested structs
    - Flatten the struct’s member’s (reducing bytecode and improve code readability) where it makes sense
        - This will need to be carefully done, having in mind the scope of changes as tests would need to be modified as well

- Reduce the number of files and merge them into a single one (where it makes sense)
    - For example: `FilAddressIdConverter` and `FilAddress` would make more sense to be part of a single file as their functionality is revolves around `FilAddress` struct and is related

-  Modify the API methods where there's a need
   - For example: https://github.com/filecoin-project/filecoin-solidity/issues/26 could be solved in multiple ways (simply renaming the struct's member, performing calculation to get the needed end of the deal, ...)

- Replace hardcoded values with constants that have clear names and are available to the developer
   - For example: 0x1...4 address type values and their lengths

**Comment by maciejwitowski** [comment]
Approved.

**Comment by smagdali** [comment]
> Approved.

Can I just clarify, you're approving the scope of this work, rather than approving completion of the work?

**Comment by maciejwitowski** [comment]
> > Approved.
> 
> Can I just clarify, you're approving the scope of this work, rather than approving completion of the work?

Yes @smagdali , i approve the scope of work. Sorry for not making it clear!
