### ISSUE TITLE
[M4] Network and core tech (VM) upgrades support

### ISSUE THREAD

**Issue by wertikalk** [filecoin-project/filecoin-solidity#46]
Task dedicated for tracking and supporting upcoming Filecoin network upgrades (starting from NV22) - making sure the existing functionality of the `filecoin-solidity` lib is maintained, and new one is correctly added (i.e. if additional builtin-actor's methods are exposed) .

This thread will be used for news, questions, and discussion.

**Comment by a42filip** [comment]
We can start working on this on the Calibration testnet
